travis:
  secure:
    BINSTAR_TOKEN: fNe5Au+oAf4JWqa/QZ+DscESqn9KkNkMxTCaWZeXK1CCagqcqs+mGFb57s81d66X1VZWOvPPkwPqY9DIgRQ+DLIer7rE+qu5Ya91yk4dTeLGPRpExRgWC9bJcsQBX5u1nfFOaiTkvRMrOOHs9EDvUOJcrNREUjYP+/SqFpB1nhRYR0xmd9YhPktbOQBTQMwsPvFlAHMjaIPImTHzGaDVLW3ydBgRxZ4VaE0xb4uLoWCgI8TgSqqSWAccitiLeHUzYS8A6DZJW8Jgd8IG/ImzF/Dzrw9TU21nIYP0OT/6p4SkxHN2HU3IXyL9Gaq3H0LI9r/VIjZFjlP1bq91QIWRbACN4VJZ2TEwa5ozm+Y+5rsBDuXCQpBS8nLU/xheIZK3N98h5hYbcbbguXOz2QJrRq/RSQf+NpiR8ANf8ua5xIM833QGflSVH+AfpQVmRhxerdllHZtozwIgMVJTPvsZntHAb9m69Zb1R7zbpz700h5OZz3zOo7jx8RKCEXp1DoiqQm6ECpmRjfAsnWEj3BynvAvGbmeg3pc8FY+h5ApsOD83SWaPn6xvdB46lh25bKWH+sXp3v0jVHnXwgVZ6d5f7wI11ZhlL/nuyboQTzUfYsW9NJrYlSyWHRnJNnT3QHULg7UNpXoh102sfSKUeRgrzoIMT+dDE/XfpsmHmB5F1E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
